image: registry.gitlab.com/pages/hugo/hugo_extended:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY
  GHPROXY: $GHPROXY
  WEB_PORT: $WEB_PORT
  WEB_USER: $WEB_USER
  WEB_HOST: $WEB_HOST
  WEB_PATH: $WEB_PATH

stages:
  - build
  - deploy

before_script: |
  if [[ -n "$GHPROXY" ]]; then
    sed -i 's/dl-cdn.alpinelinux.org/mirrors.bfsu.edu.cn/g' /etc/apk/repositories
    
    # git config --global url."${GHPROXY}https://github.com/".insteadOf https://github.com/
    # sed -i "s@https://github.com@${GHPROXY}/https://github.com@" .gitmodules    
  fi

  apk add --no-cache openssh-client rsync

  mkdir -p docs

build:
  stage: build
  script:
    - hugo
  artifacts:
    paths:
      - docs
  only:
    - main

deploy:
  stage: deploy
  script:
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - hugo --minify
    - rsync -avz -e "ssh -p $PORT" --delete docs/* "$WEB_PORT" "${WEB_USER}@${WEB_HOST}:${WEB_PATH}/"
  dependencies:
    - build
  only:
    - main
