image: registry.gitlab.com/pages/hugo/hugo_extended:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
    - urlstatus=$(curl -s -m 3 -IL https://google.com | grep 200)
      if [ -z "${urlstatus}" ]; then
      sed -i 's/github/ghproxy.com\/https:\/\/github/g' .gitmodules
      fi
    - hugo
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
