---
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CLOUDFLARE_API_TOKEN: $CLOUDFLARE_API_TOKEN

image: registry.gitlab.com/pages/hugo/hugo_extended:latest

stages:
- deploy

before_script: |
  apk update
  apk add --no-cache bash npm curl
  npm install -g wrangler@latest

deploy:
  stage: deploy
  script: |
    bash ./.deploy.sh -d

  only:
  - main
  - more
