image: registry.gitlab.com/pages/hugo/hugo_extended:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
    - urlstatus=$(curl -s -m 3 -IL https://github.com | grep 200)
      if [ -z "${urlstatus}" ]; then
      git config --global url."https://ghproxy.com/https://github.com/".insteadOf https://github.com/
      fi
    - hugo
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
