baseURL               = "https://nav.skiy.net"
languageCode          = "zh-CN"
title                 = "爱开发导航"
theme                 = "WebStack-Hugo"
publishDir            = "public"
preserveTaxonomyNames = true
disablePathToLower    = true
hasCJKLanguage        = true

[params]
    author        = "Jetsung"
    description   = "爱开发导航 | 一名热爱 Linux 的软件开发者"
    upload        = ""                                   # 左侧导航栏的"网站提交"
    about         = "https://www.idev.top/p/about"       # 左侧导航栏的"关于导航"页面(./about)
    contact       = ""                                   # 右侧关于我们    
    repository    = "https://github.com/forkdo/WebStack-Hugo"  
    enablePreLoad = true		    		             # 网站完全打开前预加载动画
    textPreLoad   = "爱开发导航" 		                   # 预加载的动画文字, 只有当enablePreLoad=true时生效
    expandSidebar = false                                # 默认展开左侧边导航栏
    logosPath     = "assets/images/logos"			     # 网站每个导航地址logo存放地址
    defaultLogo   = "assets/images/logos/default.webp"   # logo图片资源不存在或者错误时, 默认显示的logo; 该参数如为空,将会一直加载对应的logo,直至成功
    nightMode     = false                                # 默认站点为深色(夜间)模式
    yiyan         = false                                # 一言
    search        = false                                # 默认启用搜索


[params.seo]    
    baiduhmid     = ''             # 百度统计 hm.src 的 ID
    baiduSiteVer  = ''             # 百度HTML标签验证(baidu-site-verification)

    tj51laid        = 'Jz7i5wL6XoAnB4Xi' # 51.LA 网站统计
    tj51lack        = 'Jz7i5wL6XoAnB4Xi'

    GoogleAdsClient = ''            # Google AdSense 

[params.qweather]
    key = ""

[params.images]
    favicon           = "assets/images/favicon.png"
    searchImageL      = "assets/images/bg-dna.jpg"		# 搜索部分浅色背景图
    searchImageD      = "assets/images/bg-dna.jpg"		# 搜索部分深色背景图
    logoExpandLight   = "assets/images/bt8-expand-light.png"
    logoExpandDark    = "assets/images/bt8-expand-dark.png"
    logoCollapseLight = "assets/images/bt.png"
    logoCollapseDark  = "assets/images/bt.png"
    
[markup.goldmark.renderer]
    unsafe = true

[params.footer]
    copyright = '[爱开发](https://www.idev.top/) <br/>本站内容源自互联网，如有内容侵犯了你的权益，请联系删除相关内容，联系邮箱：jetsungchan@gmail.com <br/>&copy; 2023 - {year} 基于 [WebStack-Hugo](https://github.com/forkdo/WebStack-Hugo) 构建，fork 自 [shenweiyan](https://github.com/shenweiyan/WebStack-Hugo)'
